// Logic regression tests with a minimal DOM and controlled animation completion.
// Run: node test.cjs. These do not replace browser rendering checks.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(), pending=[];
function element(){const attrs={},classes=new Set();return {style:{},children:[],textContent:'',classList:{add(...xs){xs.forEach(x=>classes.add(x))},remove(...xs){xs.forEach(x=>classes.delete(x))},contains:x=>classes.has(x)},setAttribute(k,v){attrs[k]=v},getAttribute:k=>attrs[k],replaceChildren(){this.children=[]},append(b){this.children.push(b)},querySelector(){return this.children[0]},focus(){},animate(frames,options){let resolve,reject;const finished=new Promise((a,b)=>{resolve=a;reject=b});const a={finished,cancel(){reject(new Error('cancel'))},resolve,frames,options};pending.push(a);return a}}}
const context=vm.createContext({document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element},matchMedia:()=>({matches:false})});
const html=fs.readFileSync(__dirname+'/index.html','utf8');
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
const run=x=>vm.runInContext(x,context),flush=async()=>{await Promise.resolve();await Promise.resolve()};
async function advance(){assert.ok(pending.length);pending.shift().resolve();await flush()}
(async()=>{assert.equal(elements.get('choices').children.length,2);const jump=run("choose('jump')");assert.equal(elements.get('choices').children.length,0);run("choose('below')");assert.equal(pending.length,1);await advance();await advance();await jump;assert.equal(run('state'),'landed');assert.equal(elements.get('actor').style.transform,'translate(634px,330px)');const next=run('finishJump()');await advance();await next;assert.equal(run('state'),'end');run('reset()');const below=run("choose('below')");await advance();await below;assert.equal(elements.get('crabs').getAttribute('visibility'),'visible');assert.equal(elements.get('wet').getAttribute('visibility'),'visible');run('watchCrabs()');elements.get('choices').children[0].onclick();assert.equal(run('state'),'end');assert.ok(elements.get('crabs').classList.contains('peace'));run('reset()');const interrupted=run("choose('jump')");run('reset()');await interrupted;pending.length=0;assert.equal(run('state'),'choice');assert.equal(elements.get('actor').style.transform,'translate(370px,330px)');assert.equal(elements.get('crabs').getAttribute('visibility'),'hidden');console.log('PASS: both routes, continuation, crab encounter, duplicate input guard, and restart during animation');})().catch(e=>{console.error(e);process.exitCode=1});
